\documentclass[a4paper,fleqn]{article}
\title{Deep sequencing codon frequency tables}
\begin{document}
\maketitle

<<eval=TRUE,echo=FALSE,term=FALSE>>=
cutoff <- 0
codon.tables <- makeVariantTables(config,'codons',cutoff=cutoff)
aa.tables <- makeVariantTables(config,'aa',cutoff=cutoff)
@

<<results=tex,fig=TRUE,include=TRUE,echo=FALSE>>=
plotTiters(config)
@

\textbf{Codon counts}

<<results=tex,fig=FALSE,echo=FALSE>>=
appendVariantTablesToLatex(config,codon.tables)
@
\clearpage

\textbf{Amino acid counts}
<<results=tex,fig=FALSE,echo=FALSE>>=
appendVariantTablesToLatex(config,aa.tables)
@

\end{document}
