#repos <- 'http://cran.md.tsukuba.ac.jp'

install.packages('rms')
install.packages('car')
install.packages('MASS')
install.packages('R.oo')
install.packages('nlme')
install.packages('LDheatmap')
install.packages('genetics')
install.packages('GenABEL')
install.packages('popbio')
install.packages('gvlma')
install.packages('coin')
install.packages('gsubfn')
install.packages('seqinr')
install.packages('googleVis')
install.packages('ROCR')
install.packages('latticeExtra')
install.packages('xtable')
install.packages('cacheSweave')
install.packages('R.utils')
#install.packages('stringr')

source("http://www.bioconductor.org/biocLite.R")
biocLite("limma")
biocLite("statmod")
biocLite("RmiR")
biocLite("hgu133plus2.db")

install.packages('R2wd')
library(R2wd)
installstatconnDCOM()

#install.packages('agce')
#install.packages('leaps')
#install.packages('corrgram')
#install.packages('vcd')
#install.packages('reshape')
#install.packages('doBy')
#install.packages('mice')
#install.packages('gvlma')
#install.packages('bootstrap')
#install.packages('gplot')
#install.packages('HH')
#install.packages('rrcov')

#install.packages('ca')



